core/urls.py
from django.urls import path
from . import views
app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('contato', views.contato, name='contato'),
    path('produto', views.produto, name='produto'),
    path('service', views.service, name='service'),
    path('charts', views.charts, name='charts'),
    path('estoque', views.estoque, name='estoque')
]

django2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

core/models.py
from django.db import models
from stdimage import StdImageField
from datetime import datetime

# Signals
from django.db.models import signals
from django.template.defaultfilters import slugify




class Base(models.Model):
    criado = models.DateField('Data de Criação', auto_now_add=True)
    modificado = models.DateField('Data de Atualização', auto_now_add=True)
    ativo = models.BooleanField('Ativo', default=True)

    class Meta:
        abstract = True


class Produto(Base):
    nome = models.CharField('Nome', max_length=100)
    preco = models.DecimalField('Preço', max_digits=8, decimal_places=2)
    estoque = models.IntegerField('Estoque')
    imagem = StdImageField('Imagem', upload_to='produtos', variations={'thumb': (124, 124)})
    slug = models.SlugField('Slug', max_length=100, blank=True, editable=False)

    def __str__(self):
        return self.nome


class PlanilhaCob(Base):
    dateNow = datetime.now().date()
    nome = models.CharField('Nome da Rota', max_length=100, default='Cidade')
    data = models.DateField('Data da Rota', default=datetime.strftime(dateNow , "%d/%m/%Y"))
    preco = models.IntegerField('Valor Cobrado', default="10.000")
    estoque = models.IntegerField('Mercadoria de Estoque', default="12.000")

    def __str__(self) -> str:
        strFormat = f'''
            {self.nome} \t {datetime.strftime(self.dateNow , "%d/%m/%Y")}
        '''
        return strFormat

def produto_pre_save(signal, instance, sender, **kwargs):
    instance.slug = slugify(instance.nome)
    

signals.pre_save.connect(produto_pre_save, sender=Produto)

core/forms.py
from django import forms
from django.core.mail.message import EmailMessage

from .models import Produto, PlanilhaCob

class ContatoForm(forms.Form):
    nome = forms.CharField(label='Nome')
    email = forms.CharField(label='E-mail')
    assunto = forms.CharField(label='Assunto')
    mensagem = forms.CharField(label='Mensagem', widget=forms.Textarea())

    def send_email(self):
        nome = self.cleaned_data['nome']
        email = self.cleaned_data['email']
        assunto = self.cleaned_data['assunto']
        mensagem = self.cleaned_data['mensagem']

        conteudo = f'Nome: {nome}\nE-mail: {email}\nAssunto: {assunto}\nMensagem: {mensagem}'

        mail = EmailMessage(
            subject='Email enviado pelo sistema Django2',
            body=conteudo,
            from_email='aldenir.sky@gmail.com',
            to=['contato@dominio.com',],
            headers={'Reply-To:': email}
        )

        mail.send()


class ProdutoModelForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['nome', 'preco', 'estoque', 'imagem']


class PlanilhaModelForm(forms.ModelForm):
    class Meta:
        model = PlanilhaCob
        fields = ['nome', 'data', 'preco', 'estoque']

core/views.py
from django.shortcuts import render
from .forms import ContatoForm, ProdutoModelForm, PlanilhaModelForm
from django.contrib import messages



def index(request):
    return render(request, 'index.html')


def contato(request):
    form = ContatoForm(request.POST or None)
    if str(request.method) == 'POST':
        if form.is_valid():
            nome = form.cleaned_data['nome']
            email = form.cleaned_data['email']
            assunto = form.cleaned_data['assunto']
            mensagem = form.cleaned_data['mensagem']
            print('Mensagem Enviada')
            print(
                f'''
                    Nome: {nome}
                    E-mail: {email}
                    Assunto {assunto}
                    Mensagem: {mensagem}''')
            messages.success(request, 'E-mail enviado.')
        else: messages.error(request, 'ERRO! O E-mail Nao foi enviado.')

    context = {
        'form': form
    }
    return render(request, 'contato.html', context)



def produto(request):

    if str(request.method) == 'POST':
        form = ProdutoModelForm(request.POST, request.FILES)
        if form.is_valid():
            prod = form.save(commit=False)

            print(f'Nome: {prod.nome}')
            print(f'Preço: {prod.preco}')
            print(f'Estoque: {prod.estoque}')
            print(f'Imagem: {prod.imagem}')

            messages.success(request, 'Produto Salvo com Sucesso.')
            form = ProdutoModelForm()
        else:
            messages.error(request,'Erro ao Salvar Produto.')
    else:
        form = ProdutoModelForm()
    
    context = {
        'form': form
    }
    return render(request, 'produto.html', context)

def estoque(request):
    if str(request.method) == "POST":
        form = PlanilhaModelForm(request.POST)
        if form.is_valid():
            prod = form.save(commit=False)
            print(
                f'''
                    Nome: {prod.nome}
                    Data da Rota: {prod.data}
                    Valor Cobrado: {prod.preco}
                    Mercadoria: {prod.estoque}
                '''
            )
            
            messages.success(request, 'Produto Salvo com Sucesso.')
            form = PlanilhaModelForm()
        else:
            messages.error(request,'Erro ao Salvar Produto.')
    else:
        form = PlanilhaModelForm()

    context = {
        'form': form
    }
    return render(request, 'estoque.html', context)


def service(line, column):
    result = ""
    count = 0
    for x in range(line):
        result += '<br>'
        for y in range(column):
            count+=1
            result += f"""<button class="btn calc" id="btn-{str(count)}" onclick=sumInt("{str(count)}")>{str(count)}</button>"""
    return result
    
def charts(request):
    
    return render(request, 'charts.html')


    

core/templates/charts.html
  {% load bootstrap4 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>charts</title>
    {% bootstrap_css %}
</head>
<body>
    <div>
        <canvas id="myChart"></canvas>
    </div>
      
    <script>
        const ctx = document.getElementById('myChart');
      
        new Chart(ctx, {
          type: 'bar',
          data: {
            labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
            datasets: [{
              label: '# of Votes',
              data: [12, 19, 3, 5, 2, 3],
              borderWidth: 1
            }]
          },
          options: {
            scales: {
              y: {
                beginAtZero: true
              }
            }
          }
        });
    </script>
    
{% bootstrap_javascript jquery='full' %}
</body>
</html>

core/templates/contato.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>contato</title>
    {% bootstrap_css %}
</head>
<body>
    <div class="container">
        <h1>Contato</h1>
        {% bootstrap_messages %}
        <form action="{% url 'contato' %}" method="post" class="form" autocomplete="off">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary"> Enviar Mensagem </button>
            {% endbuttons %}
        </form>
    </div>
    
{% bootstrap_javascript jquery='full' %}
</body>
</html>

core/templates/estoque.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static '/js/script.js' %}" type="text/javascript"></script>
    {% bootstrap_css %}
    <title>Estoque</title>
</head>
<body >
    
    <div class="container">
        <h1>Estoque</h1>
        {% bootstrap_messages %}

        <form action="{% url 'core:estoque' %}" method="post" class="form" autocomplete="off">
            {% csrf_token %}

            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class=" btn btn-primary">Cadastrar</button>
            {% endbuttons %}
        </form>

    </div>
    

{% bootstrap_javascript jquery='full' %}
</body>

</html>

core/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
</head>
<body>
    <h1>Index</h1>
</body>
</html>

core/templates/produto.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static '/js/script.js' %}" type="text/javascript"></script>
    {% bootstrap_css %}
    <title>Document</title>
</head>
<body >
    
    <div class="container">
        <h1>Produto</h1>
        {% bootstrap_messages %}

        <form action="{% url 'core:produto' %}" method="post" class="form" autocomplete="off" enctype="multipart/form-data">
            {% csrf_token %}

            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class=" btn btn-primary">Cadastrar</button>
            {% endbuttons %}
        </form>

    </div>
    

{% bootstrap_javascript jquery='full' %}
</body>

</html>